/* ═══════════════════════════════════════════════════════
   REQUIEM — terminal.js
   Content is loaded from content.json (generated by build.js).
   To add content: drop a .md file into the right content/
   subfolder, then run  node build.js  before pushing.
   ═══════════════════════════════════════════════════════ */

'use strict';

// ── DOM refs ──────────────────────────────────────────
const output   = document.getElementById('output');
const inputRow = document.getElementById('input-row');
const cmdInput = document.getElementById('cmd-input');

// ── State ─────────────────────────────────────────────
let   CONTENT    = null;
const cmdHistory = [];
let   histIdx    = -1;
let   booting    = true;

// ── Helpers ───────────────────────────────────────────

function line(text = '', cls = '') {
  const el = document.createElement('span');
  el.className = 'line' + (cls ? ' line-' + cls : '');
  el.innerHTML = text;
  output.appendChild(el);
  scrollBottom();
  return el;
}

function gap() { line('', ''); }
function scrollBottom() { window.scrollTo(0, document.body.scrollHeight); }
function echoCmd(cmd) { line(`runox@amoeboid:~$ ${cmd}`, 'echo'); }
function delay(ms) { return new Promise(r => setTimeout(r, ms)); }

function printLines(lines, interval = 20) {
  return new Promise(resolve => {
    let i = 0;
    function next() {
      if (i >= lines.length) { resolve(); return; }
      const entry = lines[i];
      const [text, cls] = Array.isArray(entry) ? entry : [entry, ''];
      setTimeout(() => { line(text, cls); i++; next(); }, interval);
    }
    next();
  });
}

function typewriter(text, cls = '', speed = 28) {
  return new Promise(resolve => {
    const el = line('', cls);
    let i = 0;
    function tick() {
      if (i > text.length) { resolve(); return; }
      el.textContent = text.slice(0, i++);
      setTimeout(tick, speed);
    }
    tick();
  });
}

function showInput() {
  inputRow.style.display = 'flex';
  cmdInput.focus();
  scrollBottom();
}

// ── Markdown renderer ─────────────────────────────────

function inlineFormat(text) {
  let s = text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  s = s.replace(/\[([^\]]+)\]\(([^)]+)\)/g,
    (_, t, u) => `<a class="line-link" href="${u}" target="_blank" rel="noopener">${t}</a>`);
  s = s.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  s = s.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  s = s.replace(/`([^`]+)`/g,
    (_, c) => `<code style="background:rgba(168,255,120,0.08);padding:0 4px;border-radius:2px;">${c}</code>`);
  return s;
}

function renderMarkdown(md) {
  const out = [];
  for (const raw of md.split('\n')) {
    const r = raw.trimEnd();
    if (r === '') { out.push(['', '']); continue; }

    const h1 = r.match(/^#\s+(.+)/);
    const h2 = r.match(/^##\s+(.+)/);
    const h3 = r.match(/^###\s+(.+)/);
    if (h1) { out.push([`  ${inlineFormat(h1[1])}`, 'bright']); continue; }
    if (h2) { out.push([`  ${inlineFormat(h2[1])}`, 'head']);   continue; }
    if (h3) { out.push([`  ${inlineFormat(h3[1])}`, 'amber']);  continue; }

    const bq = r.match(/^>\s*(.*)/);
    if (bq) { out.push([`  | ${inlineFormat(bq[1])}`, 'dim']); continue; }

    const li = r.match(/^[-*]\s+(.*)/);
    if (li) { out.push([`    . ${inlineFormat(li[1])}`, '']); continue; }

    if (/^[-]{3,}$/.test(r)) {
      out.push(['  ─────────────────────────────────────────', 'muted']);
      continue;
    }

    out.push([`  ${inlineFormat(r)}`, '']);
  }
  return out;
}

// ── Section metadata ──────────────────────────────────

const SECTION_META = {
  projects: {
    subsections: {
      ee:         { label: 'Electrical Engineering', icon: 'EE',    cls: 'amber'  },
      gamedev:    { label: 'Game Development',        icon: 'GAME',  cls: 'coral'  },
      worldbuild: { label: 'World Building',          icon: 'WORLD', cls: 'violet' },
      misc:       { label: 'Miscellaneous',           icon: 'MISC',  cls: 'bright' },
      legacy:     { label: 'Legacy // high school',   icon: 'OLD',   cls: 'muted'  },
    },
  },
  art: {
    subsections: {
      photo: { label: 'Photography', icon: 'PHO', cls: 'coral'  },
      music: { label: 'Music',       icon: 'MUS', cls: 'amber'  },
      other: { label: 'Other Work',  icon: 'ETC', cls: 'bright' },
    },
  },
  consumption: {
    subsections: {
      games: { label: 'Video Games', icon: 'GAM', cls: 'coral'  },
      media: { label: 'Media',       icon: 'MED', cls: 'violet' },
      music: { label: 'Music',       icon: 'MUS', cls: 'amber'  },
    },
  },
};

// ── File viewer ───────────────────────────────────────

let lastEntries = [];

function stripObsidian(text) {
  return text
    .replace(/!\[\[[^\]]*\]\]/g, '')
    .replace(/\[\[[^\]|]+\|([^\]]+)\]\]/g, '$1')
    .replace(/\[\[[^\]]*#([^\]]+)\]\]/g, '$1')
    .replace(/\[\[([^\]]+)\]\]/g, '$1');
}

function openViewer(title, markdown) {
  const base = (location.hostname === 'localhost' || location.hostname === '127.0.0.1') ? '' : '/PersonalSiteVK';
  const viewer = document.getElementById('viewer');
  document.getElementById('viewer-title').textContent = '// ' + title;
  document.getElementById('viewer-body').innerHTML = marked.parse(stripObsidian(markdown));
  viewer.style.display = 'flex';
  document.getElementById('viewer-body').scrollTop = 0;
  document.getElementById('viewer-close').focus();
}

function closeViewer() {
  document.getElementById('viewer').style.display = 'none';
  cmdInput.focus();
}

document.getElementById('viewer-close').addEventListener('click', closeViewer);
document.addEventListener('keydown', function(e) {
  if (e.key === 'Escape' && document.getElementById('viewer').style.display === 'flex') closeViewer();
});

// ── Content renderers ─────────────────────────────────

function renderEntries(entries, titleCls) {
  titleCls = titleCls || 'amber';
  if (!entries || entries.length === 0) {
    return [
      ['', ''],
      ['  no entries yet. drop a .md file in the folder and run build.js.', 'muted'],
      ['', ''],
    ];
  }

  lastEntries = entries;

  // Build cards directly — no placeholder/setTimeout needed
  const base = (location.hostname === 'localhost' || location.hostname === '127.0.0.1') ? '' : '/PersonalSiteVK';

  // We return a special marker and handle rendering outside printLines
  // by building cards immediately after the section header prints
  gap();
  entries.forEach(function(entry, i) {
    var card = document.createElement('div');
    card.style.cssText = 'display:flex;align-items:flex-start;gap:14px;padding:10px 14px;margin:3px 0;border:1px solid rgba(168,255,120,0.1);border-radius:3px;cursor:pointer;background:#0e120e;transition:border-color 0.15s;max-width:640px;opacity:0;animation:fadein 0.05s forwards;';

    card.addEventListener('mouseenter', function() { card.style.borderColor = 'rgba(168,255,120,0.35)'; });
    card.addEventListener('mouseleave', function() { card.style.borderColor = 'rgba(168,255,120,0.1)'; });
    card.addEventListener('click', function() { openViewer(entry.title, entry.body); });

    // thumbnail
    var thumb = document.createElement('div');
    thumb.style.cssText = 'width:80px;height:60px;flex-shrink:0;border-radius:2px;overflow:hidden;background:#141414;border:1px solid rgba(168,255,120,0.08);display:flex;align-items:center;justify-content:center;';
    if (entry.thumbnail) {
      var img = document.createElement('img');
      img.src = base + '/' + entry.thumbnail;
      img.alt = entry.title;
      img.style.cssText = 'width:100%;height:100%;object-fit:cover;display:block;';
      img.onerror = function() { thumb.innerHTML = '<span style="font-size:10px;color:#3a4a3a;font-family:\'IBM Plex Mono\',monospace;">no img</span>'; };
      thumb.appendChild(img);
    } else {
      thumb.innerHTML = '<span style="font-size:11px;color:#3a4a3a;font-family:\'IBM Plex Mono\',monospace;">' + (i + 1) + '</span>';
    }

    // text
    var info = document.createElement('div');
    info.style.cssText = 'display:flex;flex-direction:column;gap:4px;min-width:0;justify-content:center;';
    var titleEl = document.createElement('span');
    titleEl.style.cssText = 'font-family:\'IBM Plex Mono\',monospace;font-size:13px;font-weight:600;color:#a8ff78;';
    titleEl.textContent = '[' + (i + 1) + '] ' + entry.title;
    var descEl = document.createElement('span');
    descEl.style.cssText = 'font-family:\'IBM Plex Sans\',sans-serif;font-size:12px;color:#6a8a6a;line-height:1.5;';
    descEl.textContent = entry.description || 'click to open →';

    info.appendChild(titleEl);
    info.appendChild(descEl);
    card.appendChild(thumb);
    card.appendChild(info);
    output.appendChild(card);
    scrollBottom();
  });

  gap();
  line('  click a card or type its number to open', 'muted');
  gap();
  return [];
}

function subsectionMenu(sectionKey) {
  const meta = SECTION_META[sectionKey];
  const lines = [
    ['', ''],
    [`  // ${sectionKey}`, 'muted'],
    ['  subcommands:', 'dim'],
    ['', ''],
  ];
  for (const [sub, info] of Object.entries(meta.subsections)) {
    const cmd = `${sectionKey} ${sub}`;
    lines.push([`  ${cmd.padEnd(28)} ${info.label}`, 'dim']);
  }
  lines.push(['', '']);
  return lines;
}

function showSubsection(sectionKey, subKey) {
  const meta = SECTION_META[sectionKey]?.subsections[subKey];
  if (!meta) {
    printLines([['', ''], [`  unknown subcommand. try: ${sectionKey}`, 'error'], ['', '']]);
    return;
  }
  const entries = CONTENT?.[sectionKey]?.[subKey] ?? [];
  // print header first, then cards render directly via renderEntries
  printLines([
    ['', ''],
    [`  [ ${meta.icon} ]  ${meta.label.toUpperCase()}`, 'head'],
    ['  ─────────────────────────────────────────', 'muted'],
  ]).then(function() {
    renderEntries(entries, meta.cls || 'amber');
  });
}

// ── Static content ────────────────────────────────────

const ASCII_LOGO = [
  '  █████╗ ███╗   ███╗ ██████╗ ███████╗██████╗  ██████╗ ██╗██████╗ ',
  ' ██╔══██╗████╗ ████║██╔═══██╗██╔════╝██╔══██╗██╔═══██╗██║██╔══██╗',
  ' ███████║██╔████╔██║██║   ██║█████╗  ██████╔╝██║   ██║██║██║  ██║',
  ' ██╔══██║██║╚██╔╝██║██║   ██║██╔══╝  ██╔══██╗██║   ██║██║██║  ██║',
  ' ██║  ██║██║ ╚═╝ ██║╚██████╔╝███████╗██████╔╝╚██████╔╝██║██████╔╝',
  ' ╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝ ╚══════╝╚═════╝  ╚═════╝ ╚═╝╚═════╝ ',
];

const HELP_LINES = [
  ['', ''],
  ['  available commands', 'head'],
  ['  ─────────────────────────────────────────', 'muted'],
  ['  home             .  about runox', 'dim'],
  ['  projects         .  things built & building', 'dim'],
  ['  consumption      .  media log', 'dim'],
  ['  art              .  photography, music, other work', 'dim'],
  ['  help             .  show this list', 'dim'],
  ['  clear            .  clear the screen', 'dim'],
  ['', ''],
  ['  tip:  up/down  history    tab  autocomplete', 'muted'],
  ['', ''],
];

const HOME_DEFAULT = [
  ['', ''],
  ['  RUNOX', 'bright'],
  ['  electrical engineer . game developer . world-builder . artist', 'dim'],
  ['', ''],
  ['  I build things at the edge of hardware and imagination.', ''],
  ['  Circuits that do something clever. Games that pull you into worlds', ''],
  ["  I've been constructing for years. Art that doesn't explain itself.", ''],
  ['', ''],
  ['  This place -- AMOEBOID -- is my corner of the internet.', ''],
  ['  It only reveals itself to those who look.', 'dim'],
  ['  You found it. Welcome.', 'amber'],
  ['', ''],
  ['  (edit content/home/ to change this)', 'muted'],
  ['', ''],
];

function homeLines() {
  const entries = CONTENT?.home ?? [];
  if (entries.length === 0) return HOME_DEFAULT;
  const out = [['', '']];
  for (const entry of entries) {
    out.push(...renderMarkdown(entry.body));
    out.push(['', '']);
  }
  return out;
}

// ── Boot sequence ─────────────────────────────────────

async function boot() {
  try {
    const base = (location.hostname === 'localhost' || location.hostname === '127.0.0.1') ? '' : '/PersonalSiteVK';
    const res = await fetch(`${base}/content.json`);
    if (res.ok) CONTENT = await res.json();
  } catch (_) { CONTENT = {}; }

  await delay(200);

  for (const row of ASCII_LOGO) { line(row, 'ascii'); await delay(16); }

  await delay(350);
  await printLines([['', ''], ['initializing AMOEBOID...', 'dim']], 55);
  await delay(450);
  await printLines([
    ['system:  personal node of runox', 'dim'],
    ['status:  online', 'dim'],
    ['access:  public -- you found it', 'dim'],
  ], 80);
  await delay(650);

  line('', '');
  await typewriter('this place does not show itself to everyone.', 'amber', 26);
  await delay(250);
  await typewriter('you sought it. here it is.', 'dim', 30);
  await delay(700);

  await printLines([['', ''], ["type  help  to see what's here.", 'bright'], ['', '']], 55);

  booting = false;
  showInput();
}

// ── Command router ────────────────────────────────────

function runCommand(raw) {
  const input = raw.trim().toLowerCase();
  if (!input) return;

  if (cmdHistory[0] !== raw) cmdHistory.unshift(raw);
  if (cmdHistory.length > 50) cmdHistory.pop();
  histIdx = -1;

  gap();
  echoCmd(raw);

  const parts = input.split(/\s+/);
  const cmd   = parts[0];
  const sub   = parts[1] || '';

  // number — open entry from last listing
  if (/^\d+$/.test(cmd)) {
    const idx = parseInt(cmd, 10) - 1;
    if (lastEntries.length && lastEntries[idx]) {
      openViewer(lastEntries[idx].title, lastEntries[idx].body);
    } else {
      line('', '');
      line('  no entry ' + cmd + '. list a section first.', 'error');
      line('', '');
    }
    return;
  }

  switch (cmd) {
    case 'help':
      printLines(HELP_LINES);
      break;

    case 'home':
    case 'whoami':
      printLines(homeLines());
      break;

    case 'projects':
      sub && SECTION_META.projects.subsections[sub]
        ? showSubsection('projects', sub)
        : sub
          ? (line('', ''), line(`  unknown subcommand: ${sub}. try: projects`, 'error'), line('', ''))
          : printLines(subsectionMenu('projects'));
      break;

    case 'art':
      sub && SECTION_META.art.subsections[sub]
        ? showSubsection('art', sub)
        : sub
          ? (line('', ''), line(`  unknown subcommand: ${sub}. try: art`, 'error'), line('', ''))
          : printLines(subsectionMenu('art'));
      break;

    case 'consumption':
      sub && SECTION_META.consumption.subsections[sub]
        ? showSubsection('consumption', sub)
        : sub
          ? (line('', ''), line(`  unknown subcommand: ${sub}. try: consumption`, 'error'), line('', ''))
          : printLines(subsectionMenu('consumption'));
      break;

    case 'clear':
    case 'cls':
      output.innerHTML = '';
      break;

    default:
      line('', '');
      line(`  command not found: ${cmd}. type  help  for a list.`, 'error');
      line('', '');
  }
}

// ── Input handling ────────────────────────────────────

cmdInput.addEventListener('keydown', e => {
  if (booting) return;

  if (e.key === 'Enter') {
    const val = cmdInput.value;
    cmdInput.value = '';
    runCommand(val);
    return;
  }

  if (e.key === 'ArrowUp') {
    e.preventDefault();
    if (histIdx < cmdHistory.length - 1) {
      histIdx++;
      cmdInput.value = cmdHistory[histIdx];
      setTimeout(() => cmdInput.setSelectionRange(cmdInput.value.length, cmdInput.value.length), 0);
    }
    return;
  }

  if (e.key === 'ArrowDown') {
    e.preventDefault();
    if (histIdx > 0) { histIdx--; cmdInput.value = cmdHistory[histIdx]; }
    else { histIdx = -1; cmdInput.value = ''; }
    return;
  }

  if (e.key === 'Tab') {
    e.preventDefault();
    const val = cmdInput.value.trim().toLowerCase();
    const completions = [
      'home',
      'projects', 'projects ee', 'projects gamedev',
      'projects worldbuild', 'projects misc', 'projects legacy',
      'art', 'art photo', 'art music', 'art other',
      'consumption', 'consumption games', 'consumption media', 'consumption music',
      'help', 'clear',
    ];
    const match = completions.find(c => c.startsWith(val) && c !== val);
    if (match) cmdInput.value = match;
  }
});

document.addEventListener('click', () => { if (!booting) cmdInput.focus(); });

// ── Start ─────────────────────────────────────────────
boot();
